{% set version = "0.3" %}
{% set name = "heterocl-libs" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  git_url: https://github.com/Hecmay/heterocl.git
  git_tag: old
  # url: https://github.com/cornell-zhang/heterocl/archive/v0.3.tar.gz
  path: ../..

build:
  number: 0

requirements:
  build:
    # The anaconda compilers for OS X are old an annoying
    # so we rely on the platform ones for now
    # - {{ compiler('cxx') }}  # [linux]
    - cmake
    - make
  host:
    - zlib  # [linux]
    - llvmdev ==6.0.0
    - future
    - numpy ==1.16.1
    - decorator
    - networkx ==2.2
    - matplotlib ==2.2.3 
    - backports.functools_lru_cache 
    - ordered-set
    - python >=3.5
#    - keras
#    - tensorflow
#    - tensorboard =2.0.0
#    - tvm-libs
#    - tvm
#    - psutil
#    - scipy
#    - attrs
  run:
    - python >=3.5

test:
  imports:
    - ordered-set
    - numpy
  requires:
    - pytest
    - scipy
  source_files:
    - tests
  commands:
    - python -m pytest tests/

about:
  home: https://github.com/cornell-zhang/heterocl
  license: Apache2
