
# set your own path to llvm-config
#LLVM_CONFIG = 

# required lowest version for llvm
LLVM_REQ_VERSION = 40

# Specify current directory level with respect to CLAY_ROOT
ifndef LEVEL
	LEVEL := .
endif

ifndef HCL_ROOT
	CurrDir = $(shell pwd)
	HCL_ROOT = $(shell cd $(CurrDir)/$(LEVEL); pwd)
endif
HCL_PKG = $(HCL_ROOT)/pkgs
HCL_PKG_BUILD = $(HCL_ROOT)/build/pkgs
HCL_PKG_INSTALL = $(HCL_PKG_BUILD)/install
