
# set your own path to llvm-config
LLVM_CONFIG = $(shell which llvm-config-4.0 2>/dev/null || \
                      which llvm-config-5.0 2>/dev/null || \
                      which llvm-config-6.0 2>/dev/null || \
                      which llvm-config-7.0 2>/dev/null || \
                      which llvm-config-8.0 2>/dev/null || \
                      which llvm-config-9.0 2>/dev/null || \
                      which llvm-config 2>/dev/null)

# set your own path to cmake
CMAKE_CONFIG = $(shell which cmake 2> /dev/null)
CMAKE_OK = no

# set whether to use vivado hls runtime
USE_VIVADO_HLS = 1

# set whether to use sdaccel opencl runtime
USE_SDACCEL_HLS = 1

# Specify current directory level with respect to CLAY_ROOT
ifndef LEVEL
	LEVEL := .
endif

ifndef HCL_ROOT
	CurrDir = $(shell pwd)
	HCL_ROOT = $(shell cd $(CurrDir)/$(LEVEL); pwd)
endif
HCL_PKG = $(HCL_ROOT)/pkgs
HCL_PKG_BUILD = $(HCL_ROOT)/build/pkgs
HCL_PKG_INSTALL = $(HCL_PKG_BUILD)/install
HCL_PKG_LLVM =$(HCL_PKG_BUILD)/llvm
HCL_PKG_LLVM_BIN = $(HCL_PKG_LLVM)/build/bin
HCL_PKG_CMAKE_BIN = $(HCL_PKG_BUILD)/cmake/build/cmake/bin
