
# set your own path to llvm-config
#LLVM_CONFIG = 

# set your own path to cmake
CMAKE_CONFIG = $(shell which cmake)
CMAKE_OK = no

# Specify current directory level with respect to CLAY_ROOT
ifndef LEVEL
	LEVEL := .
endif

ifndef HCL_ROOT
	CurrDir = $(shell pwd)
	HCL_ROOT = $(shell cd $(CurrDir)/$(LEVEL); pwd)
endif
HCL_PKG = $(HCL_ROOT)/pkgs
HCL_PKG_BUILD = $(HCL_ROOT)/build/pkgs
HCL_PKG_INSTALL = $(HCL_PKG_BUILD)/install
HCL_PKG_LLVM =$(HCL_PKG_BUILD)/llvm
HCL_PKG_LLVM_BIN = $(HCL_PKG_LLVM)/build/bin
HCL_PKG_CMAKE_BIN = $(HCL_PKG_BUILD)/cmake/build/cmake/bin
