{% set version = "0.3" %}
{% set name = "heterocl" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  git_url: https://github.com/Hecmay/heterocl.git
  git_tag: old
  # path: ../../

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - llvmdev ==6.0.0
    - libgcc ==5.2.0
    - cmake
    - make
  host:
    - zlib  # [linux]
    - future
    - llvmdev ==6.0.0
    - libgcc ==5.2.0
    - numpy ==1.16.1
    - decorator
    - networkx ==2.2
    - matplotlib ==2.2.3 
    - backports.functools_lru_cache 
    - ordered-set
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - numpy
  requires:
    - pytest
    - scipy
    - ordered-set
  source_files:
    - tests
  commands:
    - python -m pytest tests/

about:
  home: https://github.com/cornell-zhang/heterocl
  license: Apache2
