# Set kernel name
KERNEL_NAME = App

# Set host source and headers (sds++)
HOST_SRC_CPP = host.cpp 
HOST_SRC_H = kernel.h

# Set host code include paths
HOST_INC = -I/opt/Xilinx/Vivado/2018.2.op2258646/include/
HOST_LIB = -L/opt/Xilinx/Vivado/2018.2.op2258646/lib/

# Set kernel file (sds++)
SDSOC_KERNEL_SRC = kernel.cpp
SDSOC_KERNEL_H = kernel.h

#-------------------------
# Leave the rest to harness
#-------------------------
include harness.mk

